version: '3'
 
services:
    influxdb:
        build:
            context: ./docker/influxdb
        hostname: influxdb
        ports:
            - 8086:8086
            - 8083:8083
       
        environment:
            INFLUXDB_USER: influxdb
            INFLUXDB_USER_PASSWORD: influxdb
